# Generated by Django 5.1.6 on 2025-03-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorilar_a', '0003_dori_miqdori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dori',
            name='tugash_muddati',
            field=models.DateField(),
        ),
    ]
