# Generated by Django 5.1.6 on 2025-03-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorilar_a', '0004_alter_dori_tugash_muddati'),
    ]

    operations = [
        migrations.AddField(
            model_name='dori',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dorilar/'),
        ),
    ]
